#!/usr/bin/env python3

#  ┏┓ ┏━┓╺┳╸╺┳╸┏━╸┏━┓╻ ╻
#  ┣┻┓┣━┫ ┃  ┃ ┣╸ ┣┳┛┗┳┛
#  ┗━┛╹ ╹ ╹  ╹ ┗━╸╹┗╸ ╹

from subprocess import check_output

status = check_output(['acpi'], universal_newlines=True)

if not status:
    # stands for no battery found
    fulltext = "NO BATTERY FOUND"
    percentleft = 100
else:
    # if there is more than one battery in one laptop, the percentage left is
    # available for each battery separately, although state and remaining
    # time for overall block is shown in the status of the first battery
    batteries = status.split("\n")
    state_batteries=[]
    commasplitstatus_batteries=[]
    percentleft_batteries=[]
    for battery in batteries:
        if battery!='':
            state_batteries.append(battery.split(": ")[1].split(", ")[0])
            commasplitstatus = battery.split(", ")
            percentleft_batteries.append(int(commasplitstatus[1].rstrip("%\n")))
            commasplitstatus_batteries.append(commasplitstatus)

    state = state_batteries[0]
    commasplitstatus = commasplitstatus_batteries[0]
    percentleft = int(sum(percentleft_batteries)/len(percentleft_batteries))

    if state == "Discharging":
        if percentleft < 10:
            fulltext = "<span font='monospace'>\uf579</span>"
        elif percentleft < 20:
            fulltext = "<span font='monospace'>\uf57a</span>"
        elif percentleft < 30:
            fulltext = "<span font='monospace'>\uf57b</span>"
        elif percentleft < 40:
            fulltext = "<span font='monospace'>\uf57c</span>"
        elif percentleft < 50:
            fulltext = "<span font='monospace'>\uf57d</span>"
        elif percentleft < 60:
            fulltext = "<span font='monospace'>\uf57e</span>"
        elif percentleft < 70:
            fulltext = "<span font='monospace'>\uf57f</span>"
        elif percentleft < 80:
            fulltext = "<span font='monospace'>\uf580</span>"
        elif percentleft < 90:
            fulltext = "<span font='monospace'>\uf581</span>"
        else:
            fulltext = "<span font='monospace'>\uf581</span>"
    else:
        fulltext = "<span font='monospace'>\uf492</span>"

    def color(percent):
        if percent < 10:
            return "#fb4934"
        if percent < 20:
            return "#fabd2f"
        if percent < 80:
            return "#83a598"
        return "#8ec07c"

    form =  '<span color="{}"> {}%</span>'
    fulltext += form.format(color(percentleft), percentleft)

print(fulltext)
print(fulltext)
