#!/usr/bin/env bash

#  ╺┳┓╻┏━┓┏━┓╻  ┏━┓╻ ╻   ┏┳┓┏━┓╺┳┓┏━╸
#   ┃┃┃┗━┓┣━┛┃  ┣━┫┗┳┛   ┃┃┃┃ ┃ ┃┃┣╸
#  ╺┻┛╹┗━┛╹  ┗━╸╹ ╹ ╹    ╹ ╹┗━┛╺┻┛┗━╸

temperature="$(redshift -p | grep -P -o '[0-9]+K')"
color="#d3869b"

if [[ "$(pidof redshift | wc -w)" == 0 ]]; then
  temperature="optimal"
  color="#8ec07c"
fi

if [[ ${temperature::-1} -gt "4999" ]]; then
  color="#fabd2f"
fi

echo " $temperature"
echo " $temperature"
echo "$color"
