#!/usr/bin/env bash

#  ┏━╸╺┳╸╻ ╻┏━╸┏━┓┏┓╻┏━╸╺┳╸
#  ┣╸  ┃ ┣━┫┣╸ ┣┳┛┃┗┫┣╸  ┃
#  ┗━╸ ╹ ╹ ╹┗━╸╹┗╸╹ ╹┗━╸ ╹

instance="$(fd -d 1 enp /sys/class/net/ | head -n 1)"
label=""
state="down"

if [[ -f "$instance/operstate" ]]; then
  state=$(cat "$instance/operstate")
fi

if [[ "$state" == "down" ]]; then
  echo "$label"
  echo "$label"
  echo "#fb4934"
  exit 0
fi

echo "$label"
echo "$label"
echo "#8ec07c"
