#!/usr/bin/env bash

#  ┏━╸╺┳╸╻ ╻┏━╸┏━┓┏┓╻┏━╸╺┳╸
#  ┣╸  ┃ ┣━┫┣╸ ┣┳┛┃┗┫┣╸  ┃
#  ┗━╸ ╹ ╹ ╹┗━╸╹┗╸╹ ╹┗━╸ ╹

instance_path=$(fd -d 1 enp /sys/class/net/ | head -n 1)
instance=$(rg -o '\w+$' <<<"$instance_path")
label=""
state="down"

if [[ -f "$instance_path/operstate" ]]; then
  state=$(cat "$instance_path/operstate")
fi

if [[ "$state" == "down" ]] || ! ip addr show "$instance" | rg -q 'inet'; then
  echo "$label"
  echo "$label"
  echo "#fb4934"
  exit 0
fi

echo "$label"
echo "$label"
echo "#8ec07c"
