#!/usr/bin/env bash

#  ┏━╸╺┳╸╻ ╻┏━╸┏━┓┏┓╻┏━╸╺┳╸
#  ┣╸  ┃ ┣━┫┣╸ ┣┳┛┃┗┫┣╸  ┃
#  ┗━╸ ╹ ╹ ╹┗━╸╹┗╸╹ ╹┗━╸ ╹

label=" "

if nmcli --fields type connection show --active | rg --quiet 'ethernet'; then
  echo "${label}"
  echo "${label}"
  echo "#8ec07c"
  exit 0
fi

echo "${label}"
echo "${label}"
echo "#fb4934"
