#!/usr/bin/env bash

#  ┏━╸╻╺┳╸╻ ╻╻ ╻┏┓
#  ┃╺┓┃ ┃ ┣━┫┃ ┃┣┻┓
#  ┗━┛╹ ╹ ╹ ╹┗━┛┗━┛

paginated_notifications=$(gh api notifications --paginate | jq '. | length')
notification_sum=0

case $BLOCK_BUTTON in
1) $BROWSER 'https://github.com/notifications' ;;

esac

for count in $paginated_notifications; do
  notification_sum=$((notification_sum + count))
done

if [[ -z "$notification_sum" ]]; then
  exit 0
fi

echo " $notification_sum"
echo " $notification_sum"

if [[ $notification_sum -gt 0 ]]; then
  echo "#fabd2f"
fi
