#!/usr/bin/env bash

#  ┏┳┓┏━┓╻╻
#  ┃┃┃┣━┫┃┃
#  ╹ ╹╹ ╹╹┗━╸

new_mail_directories=("$HOME"/.local/share/mail/*/Inbox/new)
mail_count=$(fd -t f . "${new_mail_directories[@]}" | wc -l)

if [[ -z "$mail_count" ]]; then
  exit 0
fi

echo " $mail_count"
echo " $mail_count"

if [[ $mail_count -gt 0 ]]; then
  echo "#fabd2f"
fi
