#!/usr/bin/env bash

#  ┏┳┓╻┏━╸┏━┓┏━┓┏━┓╻ ╻┏━┓┏┓╻┏━╸
#  ┃┃┃┃┃  ┣┳┛┃ ┃┣━┛┣━┫┃ ┃┃┗┫┣╸
#  ╹ ╹╹┗━╸╹┗╸┗━┛╹  ╹ ╹┗━┛╹ ╹┗━╸

case $BLOCK_BUTTON in
  1) pamixer --default-source -t ;;
  3) pamixer --default-source -t ;;
  4) pamixer --default-source --unmute --increase 5 ;;
  5) pamixer --default-source --unmute --decrease 5 ;;
esac

volume=$(pamixer --default-source --get-volume-human)

if [[ "$volume" =~ \[on\] ]] && [[ "$volume" =~ [0-9]*% ]]; then
  print=" ${BASH_REMATCH[*]}"
else
  print=" muted"
  color="#fb4934"
fi

if [[ "$volume" == 'muted' ]]; then
  print=" $volume"
  color="#fb4934"
else
  print=" $volume"
  color=""
fi

echo "$print"
echo "$print"
echo "$color"
