#!/usr/bin/env bash

#  ┏┳┓╻┏━╸┏━┓┏━┓┏━┓╻ ╻┏━┓┏┓╻┏━╸
#  ┃┃┃┃┃  ┣┳┛┃ ┃┣━┛┣━┫┃ ┃┃┗┫┣╸
#  ╹ ╹╹┗━╸╹┗╸┗━┛╹  ╹ ╹┗━┛╹ ╹┗━╸

color=""
mixer="default"
scontrol="Capture"
step="${1:-5%}"

case $BLOCK_BUTTON in
  1) amixer -q -D "$mixer" sset "$scontrol" toggle ;;
  3) amixer -q -D "$mixer" sset "$scontrol" toggle ;;
  4) amixer -q -D "$mixer" sset "$scontrol" "${step}+" unmute ;;
  5) amixer -q -D "$mixer" sset "$scontrol" "${step}-" unmute ;;
esac

volume=$(amixer -D "$mixer" get "$scontrol")

if [[ "$volume" =~ \[on\] ]] && [[ "$volume" =~ [0-9]*% ]]; then
  print=" ${BASH_REMATCH[*]}"
else
  print=" muted"
  color="#fabd2f"
fi

echo "$print"
echo "$print"
echo "$color"
