#!/usr/bin/env bash

#  ╻ ╻┏━┓╻  ╻ ╻┏┳┓┏━╸
#  ┃┏┛┃ ┃┃  ┃ ┃┃┃┃┣╸
#  ┗┛ ┗━┛┗━╸┗━┛╹ ╹┗━╸

# https://github.com/cdemoulins/pamixer/issues/23
# % pamixer --default-source
# % pamixer --default-source -t
# % pamixer --default-source --get-volume
# 63
# % pamixer --get-volume
# 77
# % pamixer --default-source -i 5

case $BLOCK_BUTTON in
  1) pamixer -t ;;
  3) pamixer -t ;;
  4) pamixer --unmute --increase 5 ;;
  5) pamixer --unmute --decrease 5 ;;
esac

volume=$(pamixer --get-volume-human)

if [[ "$volume" == 'muted' ]]; then
  print="  $volume"
  color="#fb4934"
else
  print="墳 $volume"
  color=""
fi

echo "$print"
echo "$print"
echo "$color"
