#!/usr/bin/env bash

#  ╻ ╻┏━┓┏┓╻
#  ┃┏┛┣━┛┃┗┫
#  ┗┛ ╹  ╹ ╹

if ip link show wg-mullvad &> /dev/null || ip link show tun0 &> /dev/null; then
  echo " "
  echo " "
  echo "#8ec07c"
else
  echo " "
  echo " "
  echo "#fb4934"
fi
