#!/usr/bin/env bash

#  ╻ ╻╻┏━╸╻
#  ┃╻┃┃┣╸ ┃
#  ┗┻┛╹╹  ╹

label="直 "
ssid=$(iwgetid -r)

if [[ -z "$ssid" ]]; then
  echo "$label"
  echo "$label"
  echo "#fb4934"
  exit 0
fi

quality=$(grep "$BLOCK_INSTANCE" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

echo "$label $ssid"
echo "$label $ssid"

if [[ $quality -gt 50 ]]; then
  echo "#8ec07c"
elif [[ $quality -gt 24 ]] && [[ $quality -lt 51 ]]; then
  echo "#fabd2f"
elif [[ $quality -lt 25 ]]; then
  echo "#fb4934"
fi
