#!/usr/bin/env bash

#  ╻ ╻╻┏━╸╻
#  ┃╻┃┃┣╸ ┃
#  ┗┻┛╹╹  ╹

active_connection=$(nmcli -f IN-USE,SSID,SIGNAL device wifi | rg '^\*')
label="直 "

if [[ -z "${active_connection}" ]]; then
  echo "${label}"
  echo "${label}"
  echo "#fb4934"
  exit 0
fi

ssid=$(echo "${active_connection}" | awk '{ print $2 }')
signal_strength=$(echo "${active_connection}" | awk '{ print $3 }')

echo "${label} ${ssid}"
echo "${label} ${ssid}"

if [[ "${signal_strength}" -gt 50 ]]; then
  echo "#8ec07c"
elif [[ "${signal_strength}" -gt 24 ]] && [[ "${signal_strength}" -lt 51 ]]; then
  echo "#fabd2f"
elif [[ "${signal_strength}" -lt 25 ]]; then
  echo "#fb4934"
fi
