#!/usr/bin/env bash

# ┏━┓┏━┓┏━╸╻ ╻
# ┣━┫┣┳┛┃  ┣━┫
# ╹ ╹╹┗╸┗━╸╹ ╹

commands=("checkupdates" "paru -Qua")
available_updates=0

for command in "${commands[@]}"; do
  updates=$(${command} | grep -vc "\[ignored\]")
  available_updates=$((available_updates + updates))
done

if [[ ${available_updates} -eq 0 ]]; then
  echo "{\"state\":\"Idle\",\"text\":\"\"}"
elif [[ ${available_updates} -lt 10 ]]; then
  echo "{\"state\":\"Warning\",\"text\":\" ${available_updates}\"}"
elif [[ ${available_updates} -ge 10 ]]; then
  echo "{\"state\":\"Critical\",\"text\":\" ${available_updates}\"}"
fi
