#!/usr/bin/env bash

# ┏━╸┏━┓╻ ╻   ┏┳┓┏━┓╺┳┓┏━╸
# ┃╺┓┣━┛┃ ┃   ┃┃┃┃ ┃ ┃┃┣╸
# ┗━┛╹  ┗━┛   ╹ ╹┗━┛╺┻┛┗━╸

vga_controllers=$(lspci -v | rg "VGA controller")

if [[ $(echo "${vga_controllers}" | wc -l) == '2' ]]; then
  echo "hGPU"
  exit 0
fi

if echo "${vga_controllers}" | rg 'NVIDIA' &> /dev/null; then
  echo "dGPU"
else
  echo "iGPU"
fi
