#!/usr/bin/env bash

#  ╺┳┓╻┏━┓┏━┓╻  ┏━┓╻ ╻   ┏┳┓┏━┓╺┳┓┏━╸
#   ┃┃┃┗━┓┣━┛┃  ┣━┫┗┳┛   ┃┃┃┃ ┃ ┃┃┣╸
#  ╺┻┛╹┗━┛╹  ┗━╸╹ ╹ ╹    ╹ ╹┗━┛╺┻┛┗━╸

label=$(redshift -p 2> /dev/null | grep -P -o '[0-9]+K')

if [[ "$(pidof redshift | wc -w)" == 0 ]]; then
  echo "{\"state\":\"Idle\",\"text\":\"6500K\"}"
  exit 0
fi

if [[ ${label::-1} -gt "4999" ]]; then
  echo "{\"state\":\"Good\",\"text\":\"${label}\"}"
  exit 0
fi

echo "{\"state\":\"Warning\",\"text\":\"${label}\"}"
