#!/usr/bin/env bash

#  ┏━┓┏━╸┏━┓┏━╸┏━╸┏┓╻┏━┓┏━┓╻ ╻┏━╸┏━┓
#  ┗━┓┃  ┣┳┛┣╸ ┣╸ ┃┗┫┗━┓┣━┫┃┏┛┣╸ ┣┳┛
#  ┗━┛┗━╸╹┗╸┗━╸┗━╸╹ ╹┗━┛╹ ╹┗┛ ┗━╸╹┗╸

if xset q | rg --quiet 'DPMS is Disabled'; then
  echo "{\"state\":\"Warning\",\"text\":\"󰒳\"}"
else
  echo "{\"state\":\"Good\",\"text\":\"󰒲\"}"
fi
