#!/usr/bin/env bash

#  ┏━┓┏━╸┏━┓┏━╸┏━╸┏┓╻┏━┓┏━┓╻ ╻┏━╸┏━┓
#  ┗━┓┃  ┣┳┛┣╸ ┣╸ ┃┗┫┗━┓┣━┫┃┏┛┣╸ ┣┳┛
#  ┗━┛┗━╸╹┗╸┗━╸┗━╸╹ ╹┗━┛╹ ╹┗┛ ┗━╸╹┗╸

current_timeout_seconds=$(xset q | rg 'timeout:' | awk '{print $2}')

if [[ "${current_timeout_seconds}" == '0' ]]; then
  echo "{\"state\":\"Warning\",\"text\":\"󰒳\"}"
else
  echo "{\"state\":\"Good\",\"text\":\"󰒲\"}"
fi
