#!/usr/bin/env bash

#  ╻ ╻┏━┓┏┓╻
#  ┃┏┛┣━┛┃┗┫
#  ┗┛ ╹  ╹ ╹

if ip link show wg-mullvad &> /dev/null || ip link show tun0 &> /dev/null; then
  echo "{\"state\":\"Good\",\"text\":\" \"}"
else
  echo "{\"state\":\"Idle\",\"text\":\" \"}"
fi
